# Generated by Django 6.0 on 2026-01-06 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', help_text='IANA timezone, e.g. Europe/Rome', max_length=50)),
                ('goal', models.CharField(choices=[('cut', 'Fat Loss'), ('bulk', 'Muscle Gain'), ('maintain', 'Maintenance')], default='maintain', max_length=20)),
                ('goal_pace', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], default='moderate', max_length=20)),
                ('target_weight_kg', models.FloatField(blank=True, null=True)),
                ('fitness_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light Activity'), ('moderate', 'Moderate Activity'), ('high', 'High Activity'), ('athlete', 'Athlete')], default='moderate', max_length=20)),
                ('sleep_target_hours', models.FloatField(blank=True, null=True)),
                ('sleep_today_hours', models.FloatField(blank=True, null=True)),
                ('water_target_liters', models.FloatField(blank=True, null=True)),
                ('water_today_liters', models.FloatField(blank=True, null=True)),
                ('daily_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('protein_g', models.PositiveIntegerField(blank=True, null=True)),
                ('carbs_g', models.PositiveIntegerField(blank=True, null=True)),
                ('fat_g', models.PositiveIntegerField(blank=True, null=True)),
                ('water_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('macro_style', models.CharField(choices=[('balanced', 'Balanced'), ('high_carb', 'High Carb'), ('high_fat', 'High Fat')], default='balanced', max_length=20)),
                ('calorie_goal_override', models.PositiveIntegerField(blank=True, help_text='Custom calorie target override', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
