# Generated by Django 6.0 on 2026-01-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='water_target_liters',
            new_name='water_target_ml',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='water_ml',
        ),
    ]
