# Generated by Django 6.0 on 2026-01-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_profile', '0002_rename_water_target_liters_profile_water_target_ml_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_sleep_log',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_water_log_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
