# Generated by Django 6.0 on 2026-01-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_profile', '0003_profile_last_sleep_log_profile_last_water_log_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_weight_log',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_sleep_log',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_water_log_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
