# Generated by Django 6.0 on 2026-01-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_profile', '0004_profile_last_weight_log_alter_profile_last_sleep_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='water_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='water_today_ml',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
