# Generated by Django 6.0 on 2026-01-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_profile', '0005_profile_water_percent_profile_water_today_ml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='water_today_liters',
        ),
    ]
