# Generated by Django 6.0 on 2026-01-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_profile', '0006_remove_profile_water_today_liters'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='calories_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_calories_log_date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sleep_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='today_calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_sleep_log',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_water_log_date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_weight_log',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
