# Generated by Django 6.0 on 2026-01-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_profile', '0008_rename_last_calories_log_date_profile_last_nutrition_log_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='daily_calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_nutrition_log_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
