# Generated by Django 6.0 on 2026-01-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_profile', '0009_alter_profile_daily_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_water_log_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
