# Generated by Django 6.0 on 2026-01-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_profile', '0010_alter_profile_last_water_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_sleep_log',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
