# Generated by Django 6.0 on 2026-01-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_profile', '0011_alter_profile_last_sleep_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_weight_log',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
