# Generated by Django 6.0 on 2026-01-10 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailywaterlog',
            old_name='amount_ml',
            new_name='total_ml',
        ),
        migrations.RenameField(
            model_name='dailyweightlog',
            old_name='kg',
            new_name='weight_kg',
        ),
    ]
